### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk#451] opened 2017-02-19 21:32 UTC
I'd like to use newer functionality like `gtk::PopoverConstraint::None` in my crate, which isn't in a released version. Once enough features have built up a new release would be greatly appreciated!

**Comment by GuillaumeGomez** [comment] 2017-02-19 21:53
It might be worth doing it, yes. Considering the amount of time it takes to make such a release, I'll try to do it in the next week but I can't promise anything.

**Comment by Susurrus** [comment] 2017-02-19 22:05
That'd work fine for me, thanks!

If it's very difficult to do a release, is there anyway I could help writing a script to automate the process?

**Comment by GuillaumeGomez** [comment] 2017-02-19 22:24
There is already one made by @gkoz. The issue isn't the update in itself but the synchronisation between the PRs update and the crates publication.

**Comment by Susurrus** [comment] 2017-02-19 22:44
I think what you're saying is that you'd like to get some more PRs into the next release? That's not a problem for me if you want to block on some features. It would be nice to know what those features are tho for a rough timeline (even though it's a feature-based not time based).

**Comment by GuillaumeGomez** [comment] 2017-02-19 23:21
No no. We generally publish a new version if there is/are big feature(s) or if some time has passed. So for this one, it'll be the second case (even if I'm very proud of the `Into<&str>` we added 😃 ).

**Comment by Susurrus** [comment] 2017-02-19 23:24
Okay, makes sense, cool! And yeah, that `Into<&str>` is a nice ergonomics win. Can't wait for the new release to update my code.

**Comment by GuillaumeGomez** [comment] 2017-02-19 23:34
I'll try to add the `Into` for every possible `Option`. And like I said, I'll try to do it in the week.

**Comment by GuillaumeGomez** [comment] 2017-03-04 14:55
And finally done!

@EPashkin: Do you want to write the blog post about the new release? If not, is there a changelogs somewhere?

**Comment by EPashkin** [comment] 2017-03-04 16:16
Sorry, I bad with literature.
Sys:
https://github.com/gtk-rs/sys/pull/35
https://github.com/gtk-rs/sys/pull/38
cairo:
https://github.com/gtk-rs/cairo/pull/102
https://github.com/gtk-rs/cairo/pull/103
https://github.com/gtk-rs/cairo/pull/106
https://github.com/gtk-rs/cairo/pull/107
gio:
https://github.com/gtk-rs/gio/pull/13
https://github.com/gtk-rs/gio/pull/14
https://github.com/gtk-rs/gio/pull/15
pango:
! https://github.com/gtk-rs/pango/pull/54
https://github.com/gtk-rs/pango/pull/55
gdk-pixbuf: none notable
gdk: none
gtk:
child properties
- https://github.com/gtk-rs/gtk/pull/394
- https://github.com/gtk-rs/gtk/pull/395
- https://github.com/gtk-rs/gtk/pull/416
https://github.com/gtk-rs/gtk/pull/399
https://github.com/gtk-rs/gtk/pull/400
https://github.com/gtk-rs/gtk/pull/414
https://github.com/gtk-rs/gtk/pull/419
https://github.com/gtk-rs/gtk/pull/425
https://github.com/gtk-rs/gtk/pull/427 Add gtk::PopoverConstraint and related Popover methods
https://github.com/gtk-rs/gtk/pull/428
https://github.com/gtk-rs/gtk/pull/433 GtkModelButton
https://github.com/gtk-rs/gtk/pull/447 Into option str
https://github.com/gtk-rs/gtk/pull/452 RadioButton & RadioMenuItem


Ignored changes for crates.io

**Comment by GuillaumeGomez** [comment] 2017-03-04 17:20
Thanks @EPashkin! I finish to write the post and then it's all good. I close this issue meanwhile.

**Closed by GuillaumeGomez** 2017-03-04 17:20 UTC
