### ISSUE TITLE
How to make `Button`s smaller than their minimal size?

### ISSUE THREAD

**Issue by MGlolenstine** [gtk-rs/gtk#968] opened 2020-03-10 12:20 UTC
I'm currently setting up some buttons, and the problem is, that I need to squeeze 10 of them into 480 pixels.

I found that the smallest width, that the button can be, is 50px. (If I resize it to less than 50, it does not change).
I'd like to change their size to 48px or even less, but I have no idea on how to proceed.

**Comment by sdroege** [comment] 2020-03-10 12:28
This is not a bug but a support request, and also generally about GTK not specific for the bindings :) Please ask this on the GTK mailing list.

**Comment by GuillaumeGomez** [comment] 2020-03-10 12:28
Closing then!

**Closed by GuillaumeGomez** 2020-03-10 12:28 UTC
