### ISSUE TITLE
Can't set ListStore as model of CellRendererCombo

### ISSUE THREAD

**Issue by fbruetting** [gtk-rs/gtk#511] opened 2017-05-18 22:16 UTC
I can specify ListStore as the TreeModel model of a ComboBox because of the `IsA<TreeModel>` trait and can even leave the Option out – but both these things don't work on CellRendererCombo, and `as TreeModel` doesn't work either. Could you please fix that, or am I misunderstanding the functionality? I'm not new to GTK but new to Rust, and the documentation sadly doesn't really help that much in a lot of cases… Here are the function definitions:

ComboBox:
`fn set_model<'a, P: IsA<TreeModel> + 'a, Q: Into<Option<&'a P>>>(&self, model: Q)`

CellRendererCombo:
`pub fn set_property_model(&self, model: Option<&TreeModel>)`

**Comment by EPashkin** [comment] 2017-05-19 04:09
Duplicate of #505
This fixed in git version by #509
Now function look `fn set_property_model<P: IsA<TreeModel> + IsA<glib::object::Object>>(&self, model: Option<&P>);` 

Properties still don't support leaving Option out: https://github.com/gtk-rs/gir/issues/363

**Comment by fbruetting** [comment] 2017-05-20 18:13
Thanks!

**Closed** 2017-05-20 18:13 UTC
