### ISSUE TITLE
ObjectExt links 404

### ISSUE THREAD

**Issue by ssbr** [gtk-rs/gtk#489] opened 2017-04-18 04:52 UTC
e.g. from http://gtk-rs.org/docs/gtk/struct.Window.html click [ObjectExt](http://gtk-rs.org/docs/gtk/trait.ObjectExt.html) --> 404.

**Comment by EPashkin** [comment] 2017-04-22 19:14
Duplicate of https://github.com/gtk-rs/gtk/issues/463

**Closed** 2017-04-22 19:17 UTC
