### ISSUE TITLE
Support GtkIconSize

### ISSUE THREAD

**Issue by aldonogueira** [gtk-rs/gtk#456] opened 2017-02-23 18:19 UTC
The function Button::new_from_icon_name() expects an i32 called size. The name suggests that this value is the image size in pixels, but it's actually an index in enum GtkIconSize.
https://developer.gnome.org/gtk3/stable/gtk3-Themeable-Stock-Images.html#GtkIconSize

There should probably exist an enum gtk::IconSize with values Menu, Button, LargeToolbar, etc.

**Comment by Susurrus** [comment] 2017-02-27 04:41
I believe this is a duplicate of #439

**Comment by GuillaumeGomez** [comment] 2017-02-27 09:58
Part of at least. Will close in favor of #439.

**Closed by GuillaumeGomez** 2017-02-27 09:58 UTC
