### ISSUE TITLE
How to disable automatic resize in a Box

### ISSUE THREAD

**Issue by MGlolenstine** [gtk-rs/gtk#967] opened 2020-03-10 12:18 UTC
I'm limited to 480x272 screensize, and whenever I put a `Entry` inside of a `Box`, that has orientation set to `Vertical`, the `Entry' resizes. It doesn't matter if I set the `width_request` to 10 or even less, it's always going to be the same width as the window. The `fill` option doesn't exist in the 'Box`, so I don't know how to proceed.

**Comment by sdroege** [comment] 2020-03-10 12:24
This is not a bug but a support request, and also generally about GTK not specific for the bindings :) Please ask this on the GTK mailing list.

**Comment by GuillaumeGomez** [comment] 2020-03-10 12:27
Closing then!

**Closed by GuillaumeGomez** 2020-03-10 12:27 UTC
