### ISSUE TITLE
gtk::Assistant don't close

### ISSUE THREAD

**Issue by hetogs** [gtk-rs/gtk#1038] opened 2020-07-24 19:39 UTC
In crate version 0.9 we need to call `gtk::GtkWindow::close()` instead `gtk::Widget::destroy()` because `destroy()` is marked as `unsafe` but with `gtk::Assistant` call to this function do nothing, the assistant do not close.

**Comment by sdroege** [comment] 2020-07-25 07:37
@ebassi What's the correct way of closing an assistant?

**Comment by sdroege** [comment] 2020-09-11 07:17
The best place to ask about this would be on https://discourse.gnome.org . As this is not a bug or feature request, let's close it here.

**Closed by sdroege** 2020-09-11 07:17 UTC

**Comment by ebassi** [comment] 2020-09-11 10:32
Sorry, I missed the notification.

`GtkAssistant` does not allow closing itself in the middle of a progress page; if you try doing that, it will emit the "cancel" signal, which will let you handle the case. At that point, you might want to hide the assistant window, schedule an idle callback, and call `unsafe { assistant.destroy(); }` when you know nothing else is holding a reference to it.

Alternatively, you can connect to the `delete-event` signal and return `true` from your handler, which will skip the default behaviour.
